[package]
name = "nix-starter-kit"
version = "0.1.0"
description = "cli tool to generate nix flakes, shells and configurations"
license = "MIT"
keywords = ["nix","cli"]

[dependencies]
cliclack = "0.3.5"
